version: "3.7"
services:
    client:
        build:
            context: ./
            dockerfile: eng/docker/DOCKERFILE-CORE-SDK-2-1
        entrypoint: bash /eng/docker/DOCKERFILE-CORE-SDK-2-1-tests.sh
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SomePassword4u"
            ACCEPT_EULA: "Y"
