FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy all sources and build the driver
COPY build.proj ./
COPY src/ ./src/
COPY tools/ ./tools/
WORKDIR /app
RUN dotnet msbuild /p:Configuration="Release" /t:Clean,BuildAll /p:GenerateDocumentationFile=false

# build Addons
RUN dotnet msbuild /p:Configuration="Release" /t:BuildAKVNetCore /p:OSGroup=Unix /p:Platform=AnyCPU

# build and run tests
RUN dotnet msbuild /p:Configuration="Release" /t:BuildTestsNetCore /p:OSGroup=Unix /p:Platform=AnyCPU /p:TargetNetCoreVersion=netcoreapp3.1
RUN dotnet test "src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj" /p:Platform="AnyCPU" /p:Configuration="Release" /p:TestTargetOS="Unixnetcoreapp" /p:TargetNetCoreVersion="netcoreapp3.1" --no-build -v n --filter "category!=nonnetcoreapptests&category!=failing&category!=nonlinuxtests&category!=nonuaptests"
RUN dotnet test "src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj" /p:Platform="AnyCPU" /p:Configuration="Release" /p:TestTargetOS="Unixnetcoreapp" /p:TargetNetCoreVersion="netcoreapp3.1" --no-build -v n --filter "category!=nonnetcoreapptests&category!=failing&category!=nonlinuxtests&category!=nonuaptests"
